var Genres = {
  'Alternative': ['Alternative'],
  'Blues': ['Blues'],
  'Classical': ['Classical'],
  'Country': ['Country'],
  'Easy Listening': ['Easy Listening'],
  'Electronic': ['Electronic'],
  'Folk': ['Folk'],
  'Inspirational': ['Inspirational'],
  'International': ['International'],
  'Jazz': ['Jazz'],
  'Latin': ['Latin'],
  'Metal': ['Metal'],
  'Misc': ['Misc'],
  'New Age': ['New Age'],
  'Pop': ['Pop'],
  'Public Radio': ['Public Radio'],
  'R&B and Urban': ['R&B and Urban'],
  'Rap': ['Rap'],
  'Reggae': ['Reggae'],
  'Rock': ['Rock'],
  'Seasonal and Holiday': ['Seasonal and Holiday'],
  'Soundtracks': ['Soundtracks'],
  'Talk': ['Talk'],
  'Themes': ['Themes']
}
